# Changes here will be overwritten by Copier
_commit: v1.4.5
_src_path: gh:lincc-frameworks/python-project-template
author_email: carlosg@uw.edu
author_name: Carlos Garcia Jurado Suarez
create_example_module: true
custom_install: true
include_benchmarks: false
include_docs: true
include_notebooks: true
mypy_type_checking: strict
package_name: autora_doc
preferred_linter: black
project_license: MIT
project_name: autora-doc
project_organization: AutoResearch
use_gitlfs: none
use_isort: true
