# This workflow will install Python dependencies, build the package and then build the documentation.

name: Build documentation


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Dependencies
      uses: ./.github/actions/deps
      with:
        python-version: '3.10'
    - name: Install notebook requirements
      run: |
        sudo apt-get install pandoc
    - name: Build docs
      run: |
        sphinx-build -T -E -b html -d docs/build/doctrees ./docs docs/build/html
